package config

object BuildDependenciesVersions {
    const val KOTLIN = "1.4.0"
    const val APPCOMPAT = "1.1.0"
    const val MATERIAL = "1.1.0"
    const val COROUTINES = "1.3.3"
    const val ROOM = "2.2.3"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.1.0"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.2.1"
    const val CONSTRAIN_LAYOUT = "1.1.3"
    const val DAGGER = "2.27"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.7.0"
    const val LOGGING = "4.2.2"
    const val CRASHLYTICS = "2.10.1"
    const val LEAKCANARY = "2.2"
    const val SECURITY_CRYPTO = "1.0.0-rc03"
    const val GSON = "2.8.6"
    const val COORDINATOR_LAYOUT = ""
    const val VIEW_PAGE2 = ""

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.14.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.1"
    const val MOCK_WEB_SERVER = "4.2.2"
}